create extension if not exists pgcrypto;
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;
create table if not exists public.sources (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  source_type text not null default 'repository',
  homepage_url text not null,
  sitemap_url text,
  api_url text,
  terms_url text,
  robots_url text,
  attribution_text text,
  is_active boolean not null default true,
  last_synced_at timestamptz,
  sync_notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint sources_source_type_check
    check (source_type in ('directory', 'repository', 'marketplace', 'manual'))
);
create table if not exists public.repositories (
  id bigint generated by default as identity primary key,
  source_id bigint references public.sources(id) on delete set null,
  owner_name text not null,
  repository_name text not null,
  repository_url text not null unique,
  default_branch text,
  license text,
  stars integer not null default 0,
  forks integer not null default 0,
  open_issues_count integer not null default 0,
  last_pushed_at timestamptz,
  readme_excerpt text,
  repo_topics text[] not null default '{}',
  last_repo_sync_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (owner_name, repository_name)
);
create table if not exists public.skills (
  id bigint generated by default as identity primary key,
  source_id bigint not null references public.sources(id) on delete cascade,
  repository_id bigint references public.repositories(id) on delete set null,
  source_skill_id text not null,
  name text not null,
  slug text not null unique,
  short_summary text,
  long_description text,
  canonical_source_url text not null unique,
  repository_url text,
  documentation_url text,
  install_command text,
  status text not null default 'active',
  first_seen_at date,
  last_synced_at timestamptz,
  weekly_installs integer not null default 0,
  total_installs integer,
  review_count integer not null default 0,
  approved_review_count integer not null default 0,
  overall_score numeric(3, 2),
  confidence_adjusted_score numeric(3, 2),
  claimed boolean not null default false,
  faq_content jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (source_id, source_skill_id),
  constraint skills_status_check
    check (status in ('active', 'hidden', 'pending', 'deprecated'))
);
create table if not exists public.agents (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  vendor_name text,
  website_url text,
  short_description text,
  logo_url text,
  status text not null default 'active',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint agents_status_check
    check (status in ('active', 'inactive'))
);
create table if not exists public.skill_agent_compatibility (
  skill_id bigint not null references public.skills(id) on delete cascade,
  agent_id bigint not null references public.agents(id) on delete cascade,
  support_type text not null default 'listed by source',
  support_notes text,
  install_count integer not null default 0,
  last_confirmed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  primary key (skill_id, agent_id),
  constraint skill_agent_compatibility_support_type_check
    check (
      support_type in ('listed by source', 'community confirmed', 'maintainer confirmed')
    )
);
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  description text,
  parent_category_id bigint references public.categories(id) on delete set null,
  display_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);
create table if not exists public.tags (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null unique,
  tag_type text not null default 'topic',
  description text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint tags_tag_type_check
    check (tag_type in ('topic', 'task', 'agent', 'pricing', 'language', 'signal'))
);
create table if not exists public.skill_categories (
  skill_id bigint not null references public.skills(id) on delete cascade,
  category_id bigint not null references public.categories(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (skill_id, category_id)
);
create table if not exists public.skill_tags (
  skill_id bigint not null references public.skills(id) on delete cascade,
  tag_id bigint not null references public.tags(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  primary key (skill_id, tag_id)
);
create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  source_id bigint references public.sources(id) on delete set null,
  status text not null default 'running',
  started_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz,
  items_found integer not null default 0,
  items_created integer not null default 0,
  items_updated integer not null default 0,
  errors_count integer not null default 0,
  raw_snapshot_path text,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint sync_runs_status_check
    check (status in ('running', 'completed', 'failed', 'partial'))
);
create trigger set_sources_updated_at
before update on public.sources
for each row execute function public.set_updated_at();
create trigger set_repositories_updated_at
before update on public.repositories
for each row execute function public.set_updated_at();
create trigger set_skills_updated_at
before update on public.skills
for each row execute function public.set_updated_at();
create trigger set_agents_updated_at
before update on public.agents
for each row execute function public.set_updated_at();
create trigger set_skill_agent_compatibility_updated_at
before update on public.skill_agent_compatibility
for each row execute function public.set_updated_at();
create trigger set_categories_updated_at
before update on public.categories
for each row execute function public.set_updated_at();
create trigger set_tags_updated_at
before update on public.tags
for each row execute function public.set_updated_at();
create trigger set_sync_runs_updated_at
before update on public.sync_runs
for each row execute function public.set_updated_at();
alter table public.sources enable row level security;
alter table public.repositories enable row level security;
alter table public.skills enable row level security;
alter table public.agents enable row level security;
alter table public.skill_agent_compatibility enable row level security;
alter table public.categories enable row level security;
alter table public.tags enable row level security;
alter table public.skill_categories enable row level security;
alter table public.skill_tags enable row level security;
alter table public.sync_runs enable row level security;
create policy "Public read sources"
on public.sources
for select
using (true);
create policy "Public read repositories"
on public.repositories
for select
using (true);
create policy "Public read skills"
on public.skills
for select
using (status = 'active');
create policy "Public read agents"
on public.agents
for select
using (status = 'active');
create policy "Public read skill agent compatibility"
on public.skill_agent_compatibility
for select
using (true);
create policy "Public read categories"
on public.categories
for select
using (true);
create policy "Public read tags"
on public.tags
for select
using (true);
create policy "Public read skill categories"
on public.skill_categories
for select
using (true);
create policy "Public read skill tags"
on public.skill_tags
for select
using (true);
create policy "Public read sync runs"
on public.sync_runs
for select
using (true);
