create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  avatar_url text,
  bio text,
  github_username text,
  is_github_linked boolean not null default false,
  role text not null default 'user',
  trust_score integer not null default 0,
  badge_summary jsonb not null default '[]'::jsonb,
  account_status text not null default 'active',
  joined_at timestamptz not null default timezone('utc', now()),
  last_active_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint user_profiles_role_check
    check (role in ('user', 'moderator', 'admin')),
  constraint user_profiles_account_status_check
    check (account_status in ('active', 'limited', 'suspended', 'banned'))
);

create or replace function public.handle_new_auth_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_profiles (
    id,
    display_name,
    avatar_url
  )
  values (
    new.id,
    coalesce(
      new.raw_user_meta_data ->> 'full_name',
      split_part(coalesce(new.email, ''), '@', 1),
      'New user'
    ),
    new.raw_user_meta_data ->> 'avatar_url'
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_auth_user();

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  skill_id bigint not null references public.skills(id) on delete cascade,
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  agent_id bigint references public.agents(id) on delete set null,
  review_title text,
  overall_rating integer not null,
  setup_rating integer,
  documentation_rating integer,
  output_quality_rating integer,
  reliability_rating integer,
  value_for_effort_rating integer,
  use_case text,
  experience_level text,
  would_recommend text not null,
  pros text not null,
  cons text not null,
  review_body text,
  proof_of_use_type text,
  proof_of_use_url text,
  moderation_status text not null default 'pending',
  moderation_notes text,
  published_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (skill_id, user_id),
  constraint reviews_overall_rating_check
    check (overall_rating between 1 and 5),
  constraint reviews_setup_rating_check
    check (setup_rating is null or setup_rating between 1 and 5),
  constraint reviews_documentation_rating_check
    check (documentation_rating is null or documentation_rating between 1 and 5),
  constraint reviews_output_quality_rating_check
    check (output_quality_rating is null or output_quality_rating between 1 and 5),
  constraint reviews_reliability_rating_check
    check (reliability_rating is null or reliability_rating between 1 and 5),
  constraint reviews_value_for_effort_rating_check
    check (value_for_effort_rating is null or value_for_effort_rating between 1 and 5),
  constraint reviews_experience_level_check
    check (
      experience_level is null or
      experience_level in ('beginner', 'intermediate', 'advanced')
    ),
  constraint reviews_would_recommend_check
    check (would_recommend in ('yes', 'no', 'with_caveats')),
  constraint reviews_proof_of_use_type_check
    check (
      proof_of_use_type is null or
      proof_of_use_type in ('url', 'upload', 'text')
    ),
  constraint reviews_moderation_status_check
    check (moderation_status in ('pending', 'approved', 'rejected', 'escalated'))
);

create table if not exists public.review_votes (
  id bigint generated by default as identity primary key,
  review_id bigint not null references public.reviews(id) on delete cascade,
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  vote_type text not null,
  created_at timestamptz not null default timezone('utc', now()),
  unique (review_id, user_id),
  constraint review_votes_vote_type_check
    check (vote_type in ('helpful', 'not_helpful'))
);

create trigger set_user_profiles_updated_at
before update on public.user_profiles
for each row execute function public.set_updated_at();

create trigger set_reviews_updated_at
before update on public.reviews
for each row execute function public.set_updated_at();

alter table public.user_profiles enable row level security;
alter table public.reviews enable row level security;
alter table public.review_votes enable row level security;

create policy "Public read user profiles"
on public.user_profiles
for select
using (true);

create policy "Users update own profile"
on public.user_profiles
for update
using (auth.uid() = id)
with check (auth.uid() = id);

create policy "Public read approved reviews"
on public.reviews
for select
using (moderation_status = 'approved');

create policy "Users read own reviews"
on public.reviews
for select
using (auth.uid() = user_id);

create policy "Users create own reviews"
on public.reviews
for insert
with check (auth.uid() = user_id);

create policy "Users update own pending reviews"
on public.reviews
for update
using (auth.uid() = user_id and moderation_status = 'pending')
with check (auth.uid() = user_id and moderation_status = 'pending');

create policy "Moderators read all reviews"
on public.reviews
for select
using (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role in ('moderator', 'admin')
  )
);

create policy "Moderators update reviews"
on public.reviews
for update
using (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role in ('moderator', 'admin')
  )
);

create policy "Public read review votes"
on public.review_votes
for select
using (true);

create policy "Users vote on reviews"
on public.review_votes
for insert
with check (auth.uid() = user_id);

create policy "Users delete own votes"
on public.review_votes
for delete
using (auth.uid() = user_id);

create index if not exists user_profiles_role_idx
  on public.user_profiles (role);

create index if not exists user_profiles_account_status_idx
  on public.user_profiles (account_status);

create index if not exists reviews_skill_id_status_created_idx
  on public.reviews (skill_id, moderation_status, created_at desc);

create index if not exists reviews_user_id_created_idx
  on public.reviews (user_id, created_at desc);

create index if not exists reviews_published_at_idx
  on public.reviews (published_at desc nulls last);

create index if not exists reviews_agent_id_idx
  on public.reviews (agent_id);

create index if not exists review_votes_review_id_idx
  on public.review_votes (review_id);
