create table if not exists public.moderation_queue (
  id bigint generated by default as identity primary key,
  item_type text not null,
  item_id text not null,
  priority integer not null default 0,
  queue_reason text not null,
  suggested_action text,
  status text not null default 'pending',
  assigned_moderator_id uuid references public.user_profiles(id) on delete set null,
  decision_notes text,
  created_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint moderation_queue_item_type_check
    check (item_type in ('review', 'comment', 'submission', 'claim', 'report', 'account')),
  constraint moderation_queue_status_check
    check (status in ('pending', 'approved', 'rejected', 'escalated'))
);

create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references public.user_profiles(id) on delete set null,
  action_type text not null,
  target_type text not null,
  target_id text not null,
  before_summary jsonb,
  after_summary jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create trigger set_moderation_queue_updated_at
before update on public.moderation_queue
for each row execute function public.set_updated_at();

alter table public.moderation_queue enable row level security;
alter table public.audit_log enable row level security;

create policy "Moderators read moderation queue"
on public.moderation_queue
for select
using (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role in ('moderator', 'admin')
  )
);

create policy "Moderators insert moderation queue"
on public.moderation_queue
for insert
with check (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role in ('moderator', 'admin')
  )
);

create policy "Moderators update moderation queue"
on public.moderation_queue
for update
using (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role in ('moderator', 'admin')
  )
);

create policy "Admins read audit log"
on public.audit_log
for select
using (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role = 'admin'
  )
);

create policy "Moderators insert audit log"
on public.audit_log
for insert
with check (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role in ('moderator', 'admin')
  )
);

create index if not exists moderation_queue_status_priority_created_idx
  on public.moderation_queue (status, priority desc, created_at desc);

create index if not exists moderation_queue_item_lookup_idx
  on public.moderation_queue (item_type, item_id);

create index if not exists audit_log_created_at_idx
  on public.audit_log (created_at desc);

create index if not exists audit_log_target_lookup_idx
  on public.audit_log (target_type, target_id);

create index if not exists audit_log_actor_idx
  on public.audit_log (actor_user_id, created_at desc);
