create table if not exists public.skill_submissions (
  id bigint generated by default as identity primary key,
  submitted_by_user_id uuid not null references public.user_profiles(id) on delete cascade,
  source_url text,
  repository_url text not null,
  proposed_name text,
  proposed_summary text,
  proposed_category text,
  proposed_agent_support jsonb not null default '[]'::jsonb,
  prefilled_name text,
  prefilled_summary text,
  prefilled_agent_support jsonb not null default '[]'::jsonb,
  prefilled_source_url text,
  moderation_notes text,
  created_skill_id bigint references public.skills(id) on delete set null,
  reviewed_by_user_id uuid references public.user_profiles(id) on delete set null,
  status text not null default 'pending',
  resolved_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint skill_submissions_status_check
    check (status in ('pending', 'approved', 'rejected', 'escalated'))
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_user_id uuid not null references public.user_profiles(id) on delete cascade,
  target_type text not null,
  target_id text not null,
  reason text not null,
  notes text,
  status text not null default 'pending',
  reviewed_by_user_id uuid references public.user_profiles(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (reporter_user_id, target_type, target_id),
  constraint reports_target_type_check
    check (target_type in ('review', 'skill')),
  constraint reports_reason_check
    check (
      reason in (
        'spam',
        'fake_review',
        'off_topic',
        'abuse_harassment',
        'wrong_listing_data',
        'copyright_issue',
        'other'
      )
    ),
  constraint reports_status_check
    check (status in ('pending', 'approved', 'rejected', 'escalated'))
);

create table if not exists public.review_requests (
  id bigint generated by default as identity primary key,
  skill_id bigint not null references public.skills(id) on delete cascade,
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  created_at timestamptz not null default timezone('utc', now()),
  unique (skill_id, user_id)
);

drop trigger if exists set_skill_submissions_updated_at on public.skill_submissions;
create trigger set_skill_submissions_updated_at
before update on public.skill_submissions
for each row execute function public.set_updated_at();

drop trigger if exists set_reports_updated_at on public.reports;
create trigger set_reports_updated_at
before update on public.reports
for each row execute function public.set_updated_at();

alter table public.skill_submissions enable row level security;
alter table public.reports enable row level security;
alter table public.review_requests enable row level security;

drop policy if exists "Users create own skill submissions" on public.skill_submissions;
create policy "Users create own skill submissions"
on public.skill_submissions
for insert
with check (auth.uid() = submitted_by_user_id);

drop policy if exists "Users read own skill submissions" on public.skill_submissions;
create policy "Users read own skill submissions"
on public.skill_submissions
for select
using (auth.uid() = submitted_by_user_id);

drop policy if exists "Moderators read skill submissions" on public.skill_submissions;
create policy "Moderators read skill submissions"
on public.skill_submissions
for select
using (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role in ('moderator', 'admin')
  )
);

drop policy if exists "Moderators update skill submissions" on public.skill_submissions;
create policy "Moderators update skill submissions"
on public.skill_submissions
for update
using (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role in ('moderator', 'admin')
  )
);

drop policy if exists "Users create own reports" on public.reports;
create policy "Users create own reports"
on public.reports
for insert
with check (auth.uid() = reporter_user_id);

drop policy if exists "Users read own reports" on public.reports;
create policy "Users read own reports"
on public.reports
for select
using (auth.uid() = reporter_user_id);

drop policy if exists "Moderators read reports" on public.reports;
create policy "Moderators read reports"
on public.reports
for select
using (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role in ('moderator', 'admin')
  )
);

drop policy if exists "Moderators update reports" on public.reports;
create policy "Moderators update reports"
on public.reports
for update
using (
  exists (
    select 1 from public.user_profiles
    where id = auth.uid()
    and role in ('moderator', 'admin')
  )
);

drop policy if exists "Users create own review requests" on public.review_requests;
create policy "Users create own review requests"
on public.review_requests
for insert
with check (auth.uid() = user_id);

drop policy if exists "Users read own review requests" on public.review_requests;
create policy "Users read own review requests"
on public.review_requests
for select
using (auth.uid() = user_id);

create index if not exists skill_submissions_status_created_at_idx
  on public.skill_submissions (status, created_at desc);

create index if not exists skill_submissions_user_created_at_idx
  on public.skill_submissions (submitted_by_user_id, created_at desc);

create index if not exists skill_submissions_created_skill_id_idx
  on public.skill_submissions (created_skill_id);

create index if not exists reports_status_created_at_idx
  on public.reports (status, created_at desc);

create index if not exists reports_target_lookup_idx
  on public.reports (target_type, target_id);

create index if not exists reports_reporter_idx
  on public.reports (reporter_user_id, created_at desc);

create index if not exists review_requests_skill_id_idx
  on public.review_requests (skill_id, created_at desc);

create index if not exists review_requests_user_id_idx
  on public.review_requests (user_id, created_at desc);
