create table if not exists public.submission_prefill_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  ip_address text,
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists submission_prefill_requests_user_created_idx
  on public.submission_prefill_requests (user_id, created_at desc);

create index if not exists submission_prefill_requests_ip_created_idx
  on public.submission_prefill_requests (ip_address, created_at desc)
  where ip_address is not null;

alter table public.submission_prefill_requests enable row level security;
